// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/ZQCard/kratos-service-base/user/internal/biz"
	"github.com/ZQCard/kratos-service-base/user/internal/conf"
	"github.com/ZQCard/kratos-service-base/user/internal/data"
	"github.com/ZQCard/kratos-service-base/user/internal/server"
	"github.com/ZQCard/kratos-service-base/user/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	smsClient := data.NewSmsServiceClient(discovery)
	dataData, cleanup, err := data.NewData(confData, logger, smsClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	addressRepo := data.NewAddressRepo(dataData, logger)
	addressUseCase := biz.NewAddressUseCase(addressRepo, logger)
	userService := service.NewUserService(userUseCase, addressUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, tracerProvider, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
